---
title: "Movies Reviews"
author: "Beverly Anne Teves BSIT-2B"
date: "2024-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(httr)
library(dplyr) 
library(polite)


Inside_Out <- "https://www.imdb.com/title/tt2096673/reviews?ref_=tt_urv"

session <- bow(Inside_Out, user_agent = "Educational")


for (url in Inside_Out){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Inside_Out_1 <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

Inside_Out_1



Inside_Out_2 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbsrdu44ajs2imt37xnalc6mqbdf4tkscczoyyfzjchfaeff6kvzqtz2mz6su6fj4uvhu"

for (url in Inside_Out_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

InsideOut_2



Inside_Out_3 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjzrht46bz234od74hpb3e7ewt5pjt6udsyou2flmjkb4drs3ynx6fvnqh4mmqeftxug6tcs"

for (url in Inside_Out_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

InsideOut_3



Inside_Out_4 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjxr3q42aj73yodb67jald7qwt5pjt6udszo43v3mzcb4dqq6ihrabrhs3ir7n62f7ig44am"


for (url in Inside_Out_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

InsideOut_4



Inside_Out_5 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjvrdu4ybzs2mkdz6pia3bpwv35pjt6udszoy3fxmjob4dy5yt7hl4ajd6455faeokiurtkg"

for (url in Inside_Out_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

InsideOut_5


Inside_Out_6 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjtrxumqaj33imdx77mapc7gvt5pjt6udsyouyvrmjnb4dqjmsh7zwwimyt2lzqvgabdnrgo"

for (url in Inside_Out_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

InsideOut_6


Inside_Out_7 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjqrpsm6ar63intx67ia3d7yvtgoq366ssyoqyfxmzndb4k4qjqg2srpqqwcdiu7wjcphjjora"

session <- bow(Inside_Out_7, user_agent = "Educational")
session

for (url in Inside_Out_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

InsideOut_7



Inside_Out_8 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjrrlr4mary3umdb4ppadb76vlcoq366ssyoi3vxnzndj4k4w64yjnqbn342wpqqw7p7ai7d6a"

session <- bow(Inside_Out_8, user_agent = "Educational")
session

for (url in Inside_Out_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

InsideOut_8


Inside_Out_9 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrzrtu4scj23uotd6poatd72uteoq366ssyom4fxmrpdv4k5geifoo7mmgoloynu7mfs3xpq4y"

session <- bow(Inside_Out_9, user_agent = "Educational")
session

for (url in Inside_Out_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

InsideOut_9


Inside_Out_10 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrwrhs4qab72mmdd6piapb74ul5pjt6udszou4flprlb4dyram565wfb3rli6ohhtjalvq6k"
session <- bow(Inside_Out_10, user_agent = "Educational")
session

for (url in Inside_Out_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

InsideOut_10


Inside_Out_11 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrxrlum6ab63ukt377pahc7suleoq366ssyomzflnbndn4k45jmjkwbi73ucz2b4dui3vo6xwa"

session <- bow(Inside_Out_11, user_agent = "Educational")
session

for (url in Inside_Out_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

InsideOut_11


#url12
Inside_Out_12 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrur3q4sbb734od77xpald7gudhoq366ss7oq4vvnbndj4k4lyoyjfwe6aapxzcxnlkev5qjwq"

session <- bow(Inside_Out_12, user_agent = "Educational")
session

for (url in Inside_Out_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

InsideOut_12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

InsideOut_12


#2nd movie

True_Detective <- "https://www.imdb.com/title/tt2356777/reviews?ref_=tt_urv"
session <- bow(True_Detective, user_agent = "Educational")


for (url in True_Detective){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_1 <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

True_Detective_1



True_Detective_2 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnrurpsmsbr73ypd57pmalcpstttfjrkiccsouyvxnjyoaeesz5rw5fllbyinb7k7d322d7a"

for (url in True_Detective_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

True_Detective_2



True_Detective_3 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzwr7r4waz53intx4pkape76vl5pjt6ubc6oy4vtmzpb4d3tayiqufbx3pagmu5l6aypmtbm"

for (url in True_Detective_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

True_Detective_3



True_Detective_4 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnztrlsm2bb63aptx6hoadcpgwt5pjt6ubc6payfzprpb4dymotnnxb3wxbkcg5i4j3z4p722"


for (url in True_Detective_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

True_Detective_4



True_Detective_5 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbzr3q4uab23qmdd7poa3a74vd5pjt6uc2zou4v5njnb4ds3r2hoonnrrare65bmypaplbnu"

for (url in True_Detective_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

True_Detective_5


True_Detective_6 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbvrhqm6cb23intv77pa3b7uvl5pjt6uc2soizfvnrnb4drlynwixw2tlf4ab6ztgdm2nl2a"

for (url in True_Detective_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

True_Detective_6


True_Detective_7 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbtr7qmsbjs3ymtx6hmatapqu35pjt6ubktoyzftnzdb4dyjsdnmir4yc3u6hoft2twuzbbu"

session <- bow(True_Detective_7, user_agent = "Educational")
session

for (url in True_Detective_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

True_Detective_7



True_Detective_8 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjyqpr4qbz62intz7hialcpsul5pjt6ud2soyzv7mjib4d3sbr2323zkr2trvvdegf7laobc"

session <- bow(True_Detective_8, user_agent = "Educational")
session

for (url in True_Detective_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

True_Detective_8


True_Detective_9 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjzr7t42ajs3umtt6ppa7b72v35pjt6uck5oe4v7mbdb4dtohm6unos3d5sxa56p23qbgz4g"

session <- bow(True_Detective_9, user_agent = "Educational")
session

for (url in True_Detective_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

True_Detective_9


True_Detective_10 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjwr3s4ybzt2iodr4pnaddpgv35pjt6ud2spe3f3mrdb4d7qjapoyir3zgy544msuzq35tgu"
session <- bow(Inside_Out_10, user_agent = "Educational")
session

for (url in True_Detective_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

True_Detective_10


True_Detective_11 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjxrlsmqar23apdv7pmadd72w3goq366ss6oe2v5nzkcr4k45tvsn5j3yx73yytpqul7tva5ga"

session <- bow(True_Detective_11, user_agent = "Educational")
session

for (url in True_Detective_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

True_Detective_11


#url12
True_Detective_12 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjvrttm6bz33eotx4hnb3b7ewt5pjt6ud2soq4flnjcb4d6kv6yy36wogikkhpxha5myzn42"

session <- bow(True_Detective_12, user_agent = "Educational")
session

for (url in True_Detective_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

True_Detective_12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

True_Detective_12

#3rd movie

Argylle <- "https://www.imdb.com/title/tt15009428/reviews?ref_=tt_urv"
session <- bow(Argylle, user_agent = "Educational")


for (url in Argylle){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_1 <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

Argylle_1



Argylle_2 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzsrlr4majz34mtr67kb7apew35pjt6ubc5oayf3mblb4dve45aymhydpfovozwq2xqodyoi"

for (url in Argylle_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

Argylle_2



Argylle_3 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzwr7r4waz53intx4pkape76vl5pjt6ubc6oy4vtmzpb4d3tayiqufbx3pagmu5l6aypmtbm"

for (url in Argylle_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

Argylle_3



Argylle_4 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnburtt4obr33epdx6heahbpsv35pjt6ubc5oazflmrjb4du7pj3zklzxeycaakrblmqqtcus"


for (url in Argylle_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

Argylle_4



Argylle_5 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjxrxr46az534mdz7piatc7wwteoq366sssoyyvxmbodb4k4wxo4yo4dvdbqeojkg5v37bvxyi"

for (url in Argylle_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

Argylle_5


Argylle_6 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjsr3smybj53yodd6poa3d7uvdfoq366sssou4flnjid54k4tmkw3usuztevwiases24oltu5i"

for (url in Argylle_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

Argylle_6


Argylle_7 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrzrhsm6bjy3akt37xfalepyu3coq366sssoyyvxnbdcv4k4ljuzlu5jkrlqheyahp7h6ijjni"

session <- bow(Argylle_7, user_agent = "Educational")
session

for (url in Argylle_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

Argylle_7



Argylle_8 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrur3r4yaj23motx7xpa7ap6vdhoq366sssoyyvznrddz4k44og6bncskm6ukyzlbwa3znqpuq"

session <- bow(Argylle_8, user_agent = "Educational")
session

for (url in Argylle_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

Argylle_8


Argylle_9 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrqqpt4uazy2mnd57xpa7cpqv35pjt6ubc5oa2vtnzdb4dqwtiounfvs4le5lrkkpgtfuy46"

session <- bow(Argylle_9, user_agent = "Educational")
session

for (url in Argylle_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

Argylle_9


Argylle_10 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzzqls44az53ektb7pna3bpgudcoq366sssoyyvtprjdz4k5xk3n4ilko5u4kjyobpdzedvyhq"
session <- bow(Inside_Out_10, user_agent = "Educational")
session

for (url in Argylle_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

Argylle_10


Argylle_11 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzurlq44ab33ektx77ia3bpeuleoq366sssoyyv7mbcdz4k4bnslioaym3kxeulbkl6f7j6mqq"

session <- bow(Argylle_11, user_agent = "Educational")
session

for (url in Argylle_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

Argylle_11


#url12
Argylle_12 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzqrtu4ucb23ypdz7hoatdpqwtjoq366sssoyyvxmzpdv4k4vnc5qcgmqbol4y26getcyd6hqq"

session <- bow(Argylle_12, user_agent = "Educational")
session

for (url in Argylle_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Argylle_12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

Argylle_12

#4th movie

Smith <- "https://www.imdb.com/title/tt14044212/reviews?ref_=tt_urv"
session <- bow(Smith, user_agent = "Educational")


for (url in Smith){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_1 <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

Smith_1



Smith_2 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzuqprmycjt3undt7xjb3a76vd5pjt6ubc5oa2f3njpb4duinr3vueouuvgcbkjxmyjngjgw"

for (url in Smith_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

Smith_2



Smith_3 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzrr3s44br73iktz7xeb7bpyvt5pjt6ubc5oazfxmznb4drrotbjkf33jfi4lzg5naguahyq"

for (url in Smith_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

Smith_3



Smith_4 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbwrxsm2ab43eodb6xpb3epwwt5pjt6ubc5oazfrmzob4d5hcmz6ffqqx5t2yspc3yjqfsis"


for (url in Smith_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

Smith_4



Smith_5 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbvrhqmwbbt2mmtd6hnb7b6mqbdf4wkwdk3oyzfxjchqris3ayvw5z4lpkpbrinieaipe"

for (url in Smith_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

Smith_5


Smith_6 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbrrxt4sbr43yptb67paxd7gwt5pjt6ubc5oazf3nbob4d7ilkhqecoqftsuitxpvjmfk2sk"

for (url in Smith_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

Smith_6


Smith_7 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjxqpq4mbb23updv6pmate7svtcoq366sssoyyvrpzpdj4k5uf6bvcle2ew3lckalrf4hp7fma"

session <- bow(Smith_7, user_agent = "Educational")
session

for (url in Smith_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

Smith_7



Smith_8 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjsqlqmscb73ent37xoahbpyvl5pjt6ubc5oa4v5pzib4dt6kyxrwpvgt3wt46n6dripxrsu"

session <- bow(Smith_8, user_agent = "Educational")
session

for (url in Smith_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

Smith_8


Smith_9 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjqrpsmoazy3uktt7xoa7b7uvdfoq366sssoyyf5nrndn4k4e3yldqfoza5lwzalfnhonbdl7y"

session <- bow(Smith_9, user_agent = "Educational")
session

for (url in Smith_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

Smith_9


Smith_10 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrwqpu42cjy2mpt567la7b7ywt5pjt6ubc5oayf5njnb4du6yajes5tvxte3wlnf4rtcnypq"
session <- bow(Inside_Out_10, user_agent = "Educational")
session

for (url in Smith_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

Smith_10


Smith_11 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrurtu4sbjs2int77hla3d7gvteoq366sssoyyv7mbpdr4k5cj4dlziy73uk2j3gtd644m74hy"

session <- bow(Smith_11, user_agent = "Educational")
session

for (url in Smith_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

Smith_11


#url12
Smith_12 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrqrhrmucjy3uot76pmaxa7qwt5pjt6ubc5oeyfrmbmb4d4zuguotqkki3qekc6awdzqe3a4"

session <- bow(Smith_12, user_agent = "Educational")
session

for (url in Smith_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Smith_12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

Smith_12

#5th movie

Wonka <- "https://www.imdb.com/title/tt6166392/reviews?ref_=tt_urv"
session <- bow(Wonka, user_agent = "Educational")


for (url in Wonka){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_1 <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

Wonka_1



Wonka_2 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnrqqlrm6azz3uod77pfaxapuu35pjt6ubc6o44ftmjcb4dxs4y6gniqkieo2eypcyzhmjeuo"

for (url in Wonka_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

Wonka



Wonka_3 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbzr3r46cj434otd77na7apwvl5pjt6ubc7pezf7nzib4dwsoxueam3nuhgzhv6iyp2onrp6"

for (url in Wonka_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}
Wonka_3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

Wonka_3



Wonka_4 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbqqpq42bbs2intx4peatap6vl5pjt6ubc7pa3v5mjob4dxtbjcbmlzbf4pbnfbvtlloejyk"


for (url in Wonka_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

Wonka_4



Wonka_5 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjzrhq4oar23qktd7xob7bp4wt5pjt6ubc6oqyfzmjob4drglxh4gaqu375yyc2jwwvpmheq"

for (url in Wonka_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

Wonka_5


Wonka_6 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjtrdtm4az53undt6xfadb7yutgoq366sssou3v5mjocv4k5l3thpeaj25rdmyt34bltaqtmri"

for (url in Wonka_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

Wonka_6


Wonka_7 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrzqls44ars3mpd367mala7uwt5pjt6ubc6oa2flprcb4dzwtsvadxit7qgivamzqwqirota"

session <- bow(Wonka_7, user_agent = "Educational")
session

for (url in Wonka_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

Wonka_7



Wonka_8 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrxrdqmycbz3mptv7xfa7cpqu35pjt6ubc6oq2vxnjdb4d2rstdwsda4t5lrloneeg2zk4gm"

session <- bow(Wonka_8, user_agent = "Educational")
session

for (url in Wonka_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

Wonka_8


Wonka_9 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrsrptmucb73yndz67paha7guteoq366sssou4v3prldf4k5c4eg6xn3oe4iu42cdfjqnsu4ha"

session <- bow(Wonka_9, user_agent = "Educational")
session

for (url in Wonka_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

Wonka_9


Wonka_10 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzyrdr46br43iot37hpadcpqvd5pjt6ubc6oayvjmjmb4ds4pd2cm6nhbsoyspwrnjf4s5q4"
session <- bow(Wonka_10, user_agent = "Educational")
session

for (url in Wonka_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

Wonka_10


Wonka_11 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzwrltmqcbt3iod76heb3d72ud5pjt6ubc6oiyf7mjjb4d4knricwzs44dlkf3rw6xaia7yy"

session <- bow(Wonka_11, user_agent = "Educational")
session

for (url in Wonka_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

Wonka_11


#url12
Wonka_12 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzurhu4obzy3ukd777iaxbpewthoq366sssou3vjmjodb4k4n3qozdrroq4q4gtmda6smnu7xi"

session <- bow(Wonka_12, user_agent = "Educational")
session

for (url in Wonka_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Wonka_12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

Wonka_12

#6th movie

Fargo <- "https://www.imdb.com/title/tt2802850/reviews?ref_=tt_urv"
session <- bow(Fargo, user_agent = "Educational")


for (url in Fargo){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_1 <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

Fargo_1



Fargo_2 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnrqqltmqbz53ykt37xoapc7sv35pjt6uc22ouzftmjlb4dy45rmknnmhg6yiskiwreo7jq5k"

for (url in Fargo_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

Fargo_2



Fargo_3 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzwrpq4qbb52mpdr6xoa7b7svl5pjt6uc22om3flnrcb4du3bj5kx6bvy6klgv34unda7fx6"

for (url in Fargo_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}
Fargo_3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

Fargo_3



Fargo_4 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnztqlr4saj62intb4hja7dpwu35pjt6uc2zoezfzmzpb4d5r3xeqaipeejrvxjjiykysqgce"


for (url in Fargo_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

Fargo_4



Fargo_5 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzrrpr4obb73ymdr6heb7bpetttfjrkkck2oiyv3nzyobqscasoq5vzttfnqydqkujke3ta"

for (url in Fargo_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

Fargo_5


Fargo_6 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbzrltm4ab43unt54hjatap4vd5pjt6uc26om2f7nbob4d242bs7vpe24os2gl62fnpdusly"

for (url in Fargo_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

Fargo_6


Fargo_7 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbxrdsmoar23aotr7xkb7a76ud5pjt6ud2spe4fznrdb4dtylzgujcr5oq4q4ztgutj2t3wm"

session <- bow(Fargo_7, user_agent = "Educational")
session

for (url in Fargo_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

Fargo_7



Fargo_8 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbsrltm4ajt3antb6xoale7qwt5pjt6ucs2pa4fjnrnb4d3fnaiurrzcss6gkly7lctonvsi"

session <- bow(Fargo_8, user_agent = "Educational")
session

for (url in Fargo_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

Fargo_8


Fargo_9 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbqrlqmocbs3aot57xfapdpwtttfjrkqdcyo42v7nryobquovnsf7k5jkgrkj342ojcafdq"

session <- bow(Fargo_9, user_agent = "Educational")
session

for (url in Fargo_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

Fargo_9


Fargo_10 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjzr7s44aby3eod56pka7d76vtfoq366ss5oezftnjodv4k4vo2ibsonypd7dngkis7st54j3y"
session <- bow(Fargo_10, user_agent = "Educational")
session

for (url in Fargo_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

Fargo_10


Fargo_11 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjxr3tm6bzs2iodz4pja7bpgu3foq366ss5o4zvxmrmdj4k52kkwxty5qqpd2am5cuqyyd2nba"

session <- bow(Fargo_11, user_agent = "Educational")
session

for (url in Fargo_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

Fargo_11


#url12
Fargo_12 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjvqlrm6bzs34mdt77la3c74vd5pjt6ucc2oi3f5njob4d3fzxweaeenjmbvc2pxigmmr7k4"

session <- bow(Fargo_12, user_agent = "Educational")
session

for (url in Fargo_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

Fargo_12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

Fargo_12

#7th movie

divergent_1 <- "https://www.imdb.com/title/tt1840309/reviews?ref_=tt_urv"

session <- bow(divergent_1, user_agent = "Educational")


for (url in divergent_1){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

divergent_df


#url 2
divergent_2 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzsrdr4yazt2mpd56pmahbp4u35pjt6ud2spa2f3prnb4d7e3osoxxfdmtwrp2ryrw4irkbo"

for (url in divergent_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

divergent_df2


#url 3
divergent_3 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbzrhq4sbzs3amdb4hladepyud5pjt6ud2spa2v5pzkb4dv5yoq7lp4ozslytq5dteuvb4iy"

for (url in divergent_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

divergent_df3


#url 4
divergent_4 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKeyg4w6ddbmqyzdo6ic4oxwjnbsrxsm6bb23ekd56xia3cpgw35pjt6uds6oqyftmrnb4d7njkmardrvodbdqqfz2qgxu6g6"


for (url in divergent_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

divergent_df4


#url 5
divergent_5 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbqrtrmqbz23emtv7pnaxbpgv35pjt6ud2spe2flmrjb4dwnwnsvygibe6ss632l7rzivdhm"

for (url in divergent_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

divergent_df5

#url 6
divergent_6 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbrrlr4wbj22ipd377mapd7uul5pjt6uds5o42f5mrlb4d7nobd4yz6dwui2p366g5ox3u3o"

for (url in divergent_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

divergent_df6

#url 7
divergent_7 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjwrhum2cb23mktb77iapc7ywt5pjt6uds3oeyv7nrnb4d2czpmmpywn4vpnkp4ztp76atay"

session <- bow(divergent_7, user_agent = "Educational")
session

for (url in divergent_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

divergent_df7


#url 8
divergent_8 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjur7rmsaj53endd77mb7cp4wtfoq366ssyoa4v3nrdd54k5mvdeqgvrjrzrud7pau6saqfupy"

session <- bow(divergent_8, user_agent = "Educational")
session

for (url in divergent_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

divergent_df8

#url 9
divergent_9 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjsrxq42ars3ymtz67ja3d74u35pjt6ud2spa2vjnzmb4dzi7jqgktztn3qca3hgorchquxy"

session <- bow(divergent_9, user_agent = "Educational")
session

for (url in divergent_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

divergent_df9

#url 10
divergent_10 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjqrtum4br33eod76pka7cpwwt5pjt6uc26oeyvjmrmb4drhgodautbhca7bf4vbvsraycp2"

session <- bow(divergent_10, user_agent = "Educational")
session

for (url in divergent_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

divergent_df10

#url11
divergent_11 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmryrxrm6az73endt6xnapcp2udcoq366ssyoa2frnbicv4k46rnvtvazgelvcjvuhlbdmsonvy"

session <- bow(divergent_11, user_agent = "Educational")
session

for (url in divergent_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

divergent_df11


#url12
divergent_12 <- "https://www.imdb.com/title/tt1840309/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrwqlr4qajy3umd77hfaddp4w3hoq366ssyoeyvvpzldj4k5i75gcbzd2eirsbhk6vkupq57wq"

session <- bow(divergent_12, user_agent = "Educational")
session

for (url in divergent_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

divergent_df12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

divergent_df12

#8th movie

pussnboots_1 <- "https://www.imdb.com/title/tt3915174/reviews?ref_=tt_urv"

session <- bow(pussnboots_1, user_agent = "Educational")

#url 1
for (url in pussnboots_1){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

pussnboots_df


#url 2
pussnboots_2 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzvqltmyars3ikd57xjb7c7yv35pjt6ubktou4vvnjdb4dqjgyyo7ci5i5gce2ur66cibz36"

for (url in pussnboots_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

pussnboots_df2


#url 3
pussnboots_3 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbqr3rmscj53yndv6hiapdp2wt5pjt6ubksom2fvprcb4d6rdxh3ndafvnhsotfpxb456ijq"

for (url in pussnboots_3){
  page <- read_html(url)
  
  names3 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date3 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating3 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews3 <- page %>%html_nodes("a.title")%>%html_text()
  content3 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df3 <- data.frame(
  Name = names3[1:25],
  Date = date3 [1:25],
  Rating = rating3 [1:25],
  Reviews = reviews3 [1:25],
  Content = content3[1:25]
)

pussnboots_df3


#url 4
pussnboots_4 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjsr3t46ar73akdb6ppa3dpsv35pjt6ubkspayfjmbmb4d7lh2m6yp7xlgo32h6ve56tp7e6"


for (url in pussnboots_4){
  page <- read_html(url)
  
  names4 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date4 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating4 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews4 <- page %>%html_nodes("a.title")%>%html_text()
  content4 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df4 <- data.frame(
  Name = names4[1:25],
  Date = date4 [1:25],
  Rating = rating4 [1:25],
  Reviews = reviews4 [1:25],
  Content = content3[1:25]
)

pussnboots_df4


#url 5
pussnboots_5 <- 'https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrzr3umuar33yodb7pmb3bpgud5pjt6ubksoe4flmbnb4dsbofscyhfgewd5fyx3hajzwizm'

for (url in pussnboots_5){
  page <- read_html(url)
  
  names5 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date5 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating5 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews5 <- page %>%html_nodes("a.title")%>%html_text()
  content5 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df5 <- data.frame(
  Name = names5[1:25],
  Date = date5 [1:25],
  Rating = rating5 [1:25],
  Reviews = reviews5 [1:25],
  Content = content5[1:25]
)

pussnboots_df5

#url 6
pussnboots_6 <- 'https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrvrxt44cby2imtr7pfaxcpuvd5pjt6ubk4pe2v7njpb4d4j2f7khfgpb7s4cgobbcgaeh32'

for (url in pussnboots_6){
  page <- read_html(url)
  
  names6 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date6 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating6 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews6 <- page %>%html_nodes("a.title")%>%html_text()
  content6 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df6 <- data.frame(
  Name = names6[1:25],
  Date = date6 [1:25],
  Rating = rating6 [1:25],
  Reviews = reviews6 [1:25],
  Content = content6[1:25]
)

pussnboots_df6

#url 7
pussnboots_7 <- "https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrtqlu4wbry2ikdb67jahe76ud5pjt6ubktoyzvtnbjb4d6nuwtg22yxgeg3ad5o3jdkhqbe"

session <- bow(pussnboots_7, user_agent = "Educational")
session

for (url in pussnboots_7){
  page <- read_html(url)
  
  names7 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date7 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating7 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews7 <- page %>%html_nodes("a.title")%>%html_text()
  content7 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df7 <- data.frame(
  Name = names7[1:25],
  Date = date7 [1:25],
  Rating = rating7 [1:25],
  Reviews = reviews7 [1:25],
  Content = content7[1:25]
)

pussnboots_df7


#url 8
pussnboots_8 <- 'https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrqrps4qbz32imdz4hlb7cpgu35pjt6ubczom2vrmzdb4dsv7h5tai24wqjhu6c3o254ux2a'

session <- bow(pussnboots_8, user_agent = "Educational")
session

for (url in pussnboots_8){
  page <- read_html(url)
  
  names8 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date8 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating8 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews8 <- page %>%html_nodes("a.title")%>%html_text()
  content8 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df8 <- data.frame(
  Name = names8[1:25],
  Date = date8 [1:25],
  Rating = rating8 [1:25],
  Reviews = reviews8 [1:25],
  Content = content8[1:25]
)

pussnboots_df8

#url 9
pussnboots_9 <- 'https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrrrlum4ab33aodd6hfb3bpyudeoq366ssto43vznjcdr4k4axsgle44esrgjvnvcywpucik2y'

session <- bow(pussnboots_9, user_agent = "Educational")
session

for (url in pussnboots_9){
  page <- read_html(url)
  
  names9 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date9 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating9 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews9 <- page %>%html_nodes("a.title")%>%html_text()
  content9 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df9 <- data.frame(
  Name = names9[1:25],
  Date = date9 [1:25],
  Rating = rating9 [1:25],
  Reviews = reviews9 [1:25],
  Content = content9[1:25]
)

pussnboots_df9

#url 10
pussnboots_10 <- 'https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzzqpsmybzz3upd767mb7ep4vtfoq366ssto44f5nrpdf4k4554up46pyet4ck3ge3n5nr466y'

session <- bow(pussnboots_10, user_agent = "Educational")
session

for (url in pussnboots_10){
  page <- read_html(url)
  
  names10 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date10 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating10 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews10 <- page %>%html_nodes("a.title")%>%html_text()
  content10 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df10 <- data.frame(
  Name = names10[1:25],
  Date = date10 [1:25],
  Rating = rating10 [1:25],
  Reviews = reviews10 [1:25],
  Content = content10[1:25]
)

pussnboots_df10

#url11
pussnboots_11 <- 'https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzwqpq42aj73amd54hoaha7evl5pjt6ubc3oq2vvnrjb4dxf3udoz6camgz2jq55ru7fs5xw'

session <- bow(pussnboots_11, user_agent = "Educational")
session

for (url in pussnboots_11){
  page <- read_html(url)
  
  names11 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date11 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating11 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews11 <- page %>%html_nodes("a.title")%>%html_text()
  content11 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df11 <- data.frame(
  Name = names11[1:25],
  Date = date11 [1:25],
  Rating = rating11 [1:25],
  Reviews = reviews11 [1:25],
  Content = content11[1:25]
)

pussnboots_df11


#url12
pussnboots_12 <- 'https://www.imdb.com/title/tt3915174/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzxrxr4mcb63amdb6xiapd72vd5pjt6ubktouzfvmrkb4dslvlvsd5cdrnskibgdjdzq5nqy'

session <- bow(pussnboots_12, user_agent = "Educational")
session

for (url in pussnboots_12){
  page <- read_html(url)
  
  names12 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date12 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating12 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews12 <- page %>%html_nodes("a.title")%>%html_text()
  content12 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

pussnboots_df12 <- data.frame(
  Name = names12[1:25],
  Date = date12 [1:25],
  Rating = rating12 [1:25],
  Reviews = reviews12 [1:25],
  Content = content12[1:25]
)

pussnboots_df12

#9th movie

saltburn_url<-'https://www.imdb.com/title/tt17351924/reviews?ref_=tt_urv' #SALTBURN
session <- bow(saltburn_url,
               user_agent = "Educational")
session

for(url in saltburn_url){
  page <- read_html(url)
 
  saltburn_names<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf<-data.frame(
    Name=saltburn_names[1:25],
    Date=saltburn_dates[1:25],
    User_Rating=saltburn_ratings[1:25],
    Content=saltburn_reviews[1:25],
    Review=saltburn_reviewsw[1:25]
  )
}

saltburn_url2<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnrvrxq4oab62motb77faxcpuul5pjt6ubc7ouzfjnrcb4d23i275p2px3kvhogku35tid4c4'
session2 <- bow(saltburn_url2,
               user_agent = "Educational")
session2

for(url in saltburn_url2){
  page <- read_html(url)
 
  saltburn_names2<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates2<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings2<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews2<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw2<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf2<-data.frame(
    Name=saltburn_names2[1:25],
    Date=saltburn_dates2[1:25],
    User_Rating=saltburn_ratings2[1:25],
    Content=saltburn_reviews2[1:25],
    Review=saltburn_reviewsw2[1:25]
  )
}

saltburn_url3<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnztrdr4uajz3mpdx77la7dpww35pjt6ubc6pe4vvprlb4dztfta4ew64mpjq5d4zkld4tvao'
 
for(url in saltburn_url3){
  page <- read_html(url)
 
  saltburn_names3<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates3<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings3<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews3<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw3<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf3<-data.frame(
    Name=saltburn_names3[1:25],
    Date=saltburn_dates3[1:25],
    User_Rating=saltburn_ratings3[1:25],
    Content=saltburn_reviews3[1:25],
    Review=saltburn_reviewsw3[1:25]
  )
}

saltburn_url4<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbwrlq46ajt3mpdr7hja7c7yul5pjt6ubc6oq2v7prnb4dzgei3zia4ibcxsk3ycjgo5fvco'
 
for(url in saltburn_url4){
  page <- read_html(url)
 
  saltburn_names4<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates4<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings4<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews4<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw4<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf4<-data.frame(
    Name=saltburn_names4[1:25],
    Date=saltburn_dates4[1:25],
    User_Rating=saltburn_ratings4[1:25],
    Content=saltburn_reviews4[1:25],
    Review=saltburn_reviewsw4[1:25]
  )
}  

saltburn_url5<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbqrhqmqcb434nd37hia7b76w35pjt6ubc6oeyvtnjob4dtxb2zl77wgkbj2twtwx2dkoeow'

for(url in saltburn_url5){
  page <- read_html(url)
 
  saltburn_names5<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates5<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings5<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews5<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw5<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf5<-data.frame(
    Name=saltburn_names5[1:25],
    Date=saltburn_dates5[1:25],
    User_Rating=saltburn_ratings5[1:25],
    Content=saltburn_reviews5[1:25],
    Review=saltburn_reviewsw5[1:25]
  )
}  

saltburn_url6<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjyqps4yab33upd377fa3cp2v3hoq366sssou2vtpzmcr4k52m4krzo4hmop55lb2cyr6qez6y'
 
  for(url in saltburn_url6){
  page <- read_html(url)
 
  saltburn_names6<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates6<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings6<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews6<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw6<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf6<-data.frame(
    Name=saltburn_names6[1:25],
    Date=saltburn_dates6[1:25],
    User_Rating=saltburn_ratings6[1:25],
    Content=saltburn_reviews6[1:25],
    Review=saltburn_reviewsw6[1:25]
  )
  }  

saltburn_url7<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjzqlumybr52mmd36xpale7sutfoq366sssoq2v5mjncv4k425zel3hpn2ny2eadmyfgwmw55y'
 
for(url in saltburn_url7){
  page <- read_html(url)
 
  saltburn_names7<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates7<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings7<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews7<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw7<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf7<-data.frame(
    Name=saltburn_names7[1:25],
    Date=saltburn_dates7[1:25],
    User_Rating=saltburn_ratings7[1:25],
    Content=saltburn_reviews7[1:25],
    Review=saltburn_reviewsw7[1:25]
  )
}  

saltburn_url8<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjwrlum2bjy3aptb7xpatc72ul5pjt6ubc6om3fxmjcb4dv3t7z3svojobkx6uhnp2dmajlq'

for(url in saltburn_url8){
  page <- read_html(url)
 
  saltburn_names8<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates8<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings8<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews8<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw8<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf8<-data.frame(
    Name=saltburn_names8[1:25],
    Date=saltburn_dates8[1:25],
    User_Rating=saltburn_ratings8[1:25],
    Content=saltburn_reviews8[1:25],
    Review=saltburn_reviewsw8[1:25]
  )
}  

saltburn_url9<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjvrds4wazt2iodr4platd7wud5pjt6ubc6ou2f3nrlb4dywe5aag3a3vlqczb5ppkmb7cng'

for(url in saltburn_url9){
  page <- read_html(url)
 
  saltburn_names9<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates9<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings9<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews9<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw9<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf9<-data.frame(
    Name=saltburn_names9[1:25],
    Date=saltburn_dates9[1:25],
    User_Rating=saltburn_ratings9[1:25],
    Content=saltburn_reviews9[1:25],
    Review=saltburn_reviewsw9[1:25]
  )
}

saltburn_url10<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjqqps46az63iotz6hjahdpeul5pjt6ubc6oi3fvnblb4dzuxef22zunrtef6ljhyqbd3tyk'

for(url in saltburn_url10){
  page <- read_html(url)
 
  saltburn_names10<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates10<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings10<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews10<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw10<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf10<-data.frame(
    Name=saltburn_names10[1:25],
    Date=saltburn_dates10[1:25],
    User_Rating=saltburn_ratings10[1:25],
    Content=saltburn_reviews10[1:25],
    Review=saltburn_reviewsw10[1:25]
  )
}

saltburn_url11<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmryqpqmmajy3andt7hlapep4udgoq366sssouyfxmrnd54k4x5mkj7xdxka5qrc2odjv6sfhni'

for(url in saltburn_url11){
  page <- read_html(url)
 
  saltburn_names11<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates11<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings11<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews11<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw11<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf11<-data.frame(
    Name=saltburn_names11[1:25],
    Date=saltburn_dates11[1:25],
    User_Rating=saltburn_ratings11[1:25],
    Content=saltburn_reviews11[1:25],
    Review=saltburn_reviewsw11[1:25]
  )
}

saltburn_url12<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrzrhq42bbs3mpt36hfb3a7ev35pjt6ubc6oq2flnblb4d4kr34jmkf2c23spfcrkgzbgly4'

for(url in saltburn_url12){
  page <- read_html(url)
 
  saltburn_names12<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates12<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings12<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews12<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw12<-page%>%html_nodes(".text.show-more__control")%>%html_text()
 
  saltburndf12<-data.frame(
    Name=saltburn_names12[1:25],
    Date=saltburn_dates12[1:25],
    User_Rating=saltburn_ratings12[1:25],
    Content=saltburn_reviews12[1:25],
    Review=saltburn_reviewsw12[1:25]
  )
}

#10 movie

cinderella_1 <- "https://www.imdb.com/title/tt1661199/reviews?ref_=tt_urv"

session <- bow(cinderella_1, user_agent = "Educational")

#url 1
for (url in cinderella_1){
  page <- read_html(url)
  
  names <- page %>%html_nodes(".display-name-link")%>%html_text()
  date <- page %>%html_nodes("span.review-date")%>%html_text()
  rating <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews <- page %>%html_nodes("a.title")%>%html_text()
  content <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df <- data.frame(
  Name = names[1:25],
  Date = date [1:25],
  Rating = rating[1:25],
  Reviews = reviews[1:25],
  Content = content[1:25]
)

cinderella_df

#url 2
cinderella_2 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzyrdu4sbzz3ikd74pnaxdp2v35pjt6ucs4pazvxmrpb4d6jgbnllcmraejbvmubqu5vkjja"

for (url in cinderella_2){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df2 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df2

#url 3
cinderella_3 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnzvrpq4ybr33qntz6hpaxc7uw35pjt6ucc6o4yfzprnb4dyk6apkbstbsspe42uj3vvtgelo"

for (url in cinderella_3){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df3 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df3

#url 4
cinderella_4 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbuqlsmqbb23ikdb4pkadb7gwt5pjt6uc26pe2vtnrlb4drjivenc7gbqr6gcfnkeuubtyjs"

for (url in cinderella_4){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df4 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df4

#url 5
cinderella_5 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjyr7qmucj43apdt6xealc7qu35pjt6ucs4o43vvmrjb4d3ocgz7cuq7bbj5xnkydaxttmn2"

for (url in cinderella_5){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df5 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df5


#url 6
cinderella_6 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjuqpu4qcbs3end77xeadap2wt5pjt6udszoa3fvnrdb4d3blyemaxfyeuwjqbr7b2ffq4yi"

for (url in cinderella_6){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df6 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df6

#url 7
cinderella_7 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjtrtq4qbr72indt7xfahcpgvlhoq366ssyomzvlnrkdf4k557jotce2eorqeicuxhlnv4cfci"

session <- bow(cinderella_7, user_agent = "Educational")
session

for (url in cinderella_6){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df7 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df7

#url 8
cinderella_8 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjrrhtmybz73mktv6pfatapuvtcoq366ss6oe4vlprldf4k5tdd7cjb7k2kjkyz232cm4o4pya"

session <- bow(cinderella_8, user_agent = "Educational")
session


for (url in cinderella_8){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df8 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df8

#url 9
cinderella_9 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrwrxqmybzs3mkt74hfb7apww35pjt6uck7oe4frprob4d45inwsn5mvvvhrmkbadfzle54a"

session <- bow(cinderella_9, user_agent = "Educational")
session


for (url in cinderella_9){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df9 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df9


#url 10
cinderella_10 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrur3q44bb43mnt37healdpgu3goq366ssyoiyvlnbjdv4k5jus6kt5hwdc2knzz563upk6qeq"

session <- bow(cinderella_10, user_agent = "Educational")
session


for (url in cinderella_9){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df9 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df9

#url 9
cinderella_9 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrwrxqmybzs3mkt74hfb7apww35pjt6uck7oe4frprob4d45inwsn5mvvvhrmkbadfzle54a"

session <- bow(divergent_12, user_agent = "Educational")
session


for (url in cinderella_9){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df9 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df9

#url 10
cinderella_10 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrsrpt4wcj43modv7xfahd7sud5pjt6udsypa4vzmzmb4d6ivanw7hhvo2tburndql4nra7a"

session <- bow(cinderella_10, user_agent = "Educational")
session


for (url in cinderella_10){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df10 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df10

#url 11
cinderella_11 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrrqpsm6ab63akt36hka7a76u35pjt6uckspazvzmjnb4dz56vtf2hjgivc3th3uo5l3ag5m"

session <- bow(cinderella_11, user_agent = "Educational")
session


for (url in cinderella_11){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df11 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df11


#url 12
cinderella_12 <- "https://www.imdb.com/title/tt1661199/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmzyrdqmubb53qpdt7xpaha7svlgoq366ssyoi2v5njkdj4k5zbyhrw2syhyya3lypmw6vkbdwa"

session <- bow(cinderella_12, user_agent = "Educational")
session


for (url in cinderella_12){
  page <- read_html(url)
  
  names2 <- page %>%html_nodes(".display-name-link")%>%html_text()
  date2 <- page %>%html_nodes("span.review-date")%>%html_text()
  rating2 <- page %>%html_nodes("span.rating-other-user-rating")%>%html_text()
  reviews2 <- page %>%html_nodes("a.title")%>%html_text()
  content2 <- page %>%html_nodes("div.text.show-more__control")%>%html_text()
}

cinderella_df12 <- data.frame(
  Name = names2[1:25],
  Date = date2 [1:25],
  Rating = rating2[1:25],
  Reviews = reviews2[1:25],
  Content = content2[1:25]
)

cinderella_df12
```





